name: Test
on:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cache HTMLProofer
        uses: actions/cache@v6
        with:
          # Cache path specified in Rakefile's `:html_proofer` task
          path: tmp/.htmlproofer
          key: htmlproofer-${{ github.run_id }}
          restore-keys: htmlproofer-
      - name: Run tests
        run: bundle exec rake test
